### ISSUE TITLE
[BUG] [PVR] Cosmetic issues in main PVR window

### ISSUE THREAD

**Issue by chcore** [jurialmunkey/skin.arctic.horizon.2#195]
In reference to the screenshot:

1. The "progress bar" in the EPG affects the colour of the text. The text  "The Love Boat" is darker than the text "Star Trek: The Next Generation", but they should probably be the same colour. Same as the "4:34PM" text which changes colour half way through
2. There is no horizontal line between the rows "Nicky, Ricky, Dicky & Dawn" and "The Love Boat" rows like there are between all of the other rows
3. There is the text "21 Chann...Now". That is probably not intended
4. Is the progress bar supposed to be coloured?
5. This one is not visible in the screenshot, but there is some intermittent flashing of light-gray when scrolling the channels in this view. It may be related to 1.

![image](https://user-images.githubusercontent.com/83099052/174024556-b1786310-7b8a-47b5-8929-74405fb2ca51.png)

**Comment by jurialmunkey** [comment]
There definitely should be a selection highlight there. Do you have proper focus highlights elsewhere in the skin - otherwise possible texturemaker didn't build.

**Comment by chcore** [comment]
I see this in the log when selecting a colour preset, maybe it's related?

```2022-06-16 20:19:44.931 T:4269    ERROR <general>: CGUIWindowSettingsCategory: failed to set focus. unknown category/setting id 'replace'.
2022-06-16 20:19:45.073 T:5375     INFO <general>: CPythonInvoker(29, /home/kodi/.kodi/addons/script.skinshortcuts/resources/lib/entry_point.py): script successfully run
2022-06-16 20:19:45.088 T:5375     INFO <general>: Python interpreter stopped
2022-06-16 20:19:45.464 T:4269     INFO <general>: Loading skin file: SkinSettings.xml, load type: LOAD_EVERY_TIME
2022-06-16 20:19:45.468 T:4269  WARNING <general>: Trying to add unsupported control type 1
2022-06-16 20:19:53.776 T:4269     INFO <general>: Loading skin file: Custom_1115_PresetColors.xml, load type: KEEP_IN_MEMORY
2022-06-16 20:19:56.215 T:5382     INFO <general>: initializing python engine.
2022-06-16 20:19:56.256 T:5382    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'TypeError'>
                                                   Error Contents: 'float' object cannot be interpreted as an integer
                                                   Traceback (most recent call last):
                                                     File "/home/kodi/.kodi/addons/script.texturemaker/script.py", line 8, in <module>
                                                       Script().run()
                                                     File "/home/kodi/.kodi/addons/script.texturemaker/resources/lib/script.py", line 111, in run
                                                       self.make_gradients(self.fg_color, self.bg_color, self.alpha)
                                                     File "/home/kodi/.kodi/addons/script.texturemaker/resources/lib/script.py", line 99, in make_gradients
                                                       self.gradient_h = make_gradient(fg_color, bg_color, alpha)
                                                     File "/home/kodi/.kodi/addons/script.texturemaker/resources/lib/script.py", line 56, in make_gradient
                                                       og_img.putalpha(og_img.getchannel('A').point(lambda x: x * alpha))
                                                     File "/usr/lib/python3.10/site-packages/PIL/Image.py", line 1723, in point
                                                       return self._new(self.im.point(lut, mode))
                                                   TypeError: 'float' object cannot be interpreted as an integer
                                                   -->End of Python script error report<--

2022-06-16 20:19:56.261 T:5382     INFO <general>: Python interpreter stopped```

**Comment by jurialmunkey** [comment]
Yes it is definitely related. Texturemaker is essential for building the textures of the skin.

Your system python packages are overriding Kodi's ones (I assume you're on some Linux distro). Kodi Matrix is set to use python 3.8.5 but you're using python 3.10 hence the error. Need to downgrade to 3.8.5

**Comment by chcore** [comment]
Yes I am using Archlinux. If I downgrade python then Kodi does not start up at all (complains about missing python 3.10.x).

I instead changed the line in the texturemaker.py script and will use that workaround for now:

`og_img.putalpha(og_img.getchannel('A').point(lambda x: int(x * alpha)))`

**Comment by jurialmunkey** [comment]
> Yes I am using Archlinux. If I downgrade python then Kodi does not start up at all (complains about missing python 3.10.x).
> 
> I instead changed the line in the texturemaker.py script and will use that workaround for now:
> 
> `og_img.putalpha(og_img.getchannel('A').point(lambda x: int(x * alpha)))`
> 
> After this the colours work (thanks!). I tried the latest changes in master and have found that all of the issues are now fixed, so I will close this issue.

Okay great, if that's the only error it is throwing then I'll patch texturemaker to convert the value to int. Alpha channel point doesn't need to be a float after the multiplication anyway.

Usually PIL differences between 3.8.5 and 3.10 are a real pain, so I was expecting way more errors to pop up after that. Glad to hear that solves it.
