### ISSUE TITLE
[BUG] Official kodi Log Viewer not working

### ISSUE THREAD

**Issue by kcook98765** [jurialmunkey/skin.arctic.horizon.2#486]
### Skin section

Other

### Current Behavior

Official kodi Log Viewer addon  (  script.logviewer v2.1.5+matrix.1 installed ) will not display log, produces an error.

### Expected Behavior

Should run log viewer.

### Steps To Reproduce

Install Kodi Log Viewer

Run Log viewer

Note, OSMC or Estuary skins work fine.

### Screenshots and Additional Info

Relevant part of logs:

2022-09-27 20:12:41.241 T:3429     INFO <general>: Loading skin file: DialogAddonInfo.xml, load type: KEEP_IN_MEMORY
2022-09-27 20:12:43.854 T:4644     INFO <general>: initializing python engine.
2022-09-27 20:12:44.994 T:3429     INFO <general>: Loading skin file: DialogSelect.xml, load type: KEEP_IN_MEMORY
2022-09-27 20:12:47.329 T:3429     INFO <general>: Loading skin file: DialogTextViewer.xml, load type: KEEP_IN_MEMORY
2022-09-27 20:12:47.453 T:4644    ERROR <general>: EXCEPTION: Non-Existent Control 1
2022-09-27 20:12:47.462 T:4644    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'RuntimeError'>
                                                   Error Contents: Non-Existent Control 1
                                                   Traceback (most recent call last):
                                                     File "/home/osmc/.kodi/addons/script.logviewer/default.py", line 5, in <module>
                                                       run()
                                                     File "/home/osmc/.kodi/addons/script.logviewer/resources/lib/navigation.py", line 69, in run
                                                       handlers[index]()
                                                     File "/home/osmc/.kodi/addons/script.logviewer/resources/lib/navigation.py", line 26, in <lambda>
                                                       handlers.append(lambda: show_log(False))
                                                     File "/home/osmc/.kodi/addons/script.logviewer/resources/lib/navigation.py", line 50, in show_log
                                                       logviewer.window(utils.ADDON_NAME, content, default=utils.is_default_window())
                                                     File "/home/osmc/.kodi/addons/script.logviewer/resources/lib/logviewer.py", line 156, in window
                                                       w.getControl(control_label).setLabel(title)
                                                   RuntimeError: Non-Existent Control 1
                                                   -->End of Python script error report<--

2022-09-27 20:12:47.519 T:4644     INFO <general>: Python interpreter stopped

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by kcook98765** [comment]
Note, if I change settings in log viewer to use "custom dialog", then it bypasses DialogTextViewer.xml and works , so I can live with this, feel free to close if you agree.

**Comment by jurialmunkey** [comment]
Full log please. No snippets. Please upload the log file itself - don't copy paste as text as it loses formatting

**Comment by kcook98765** [comment]
Here is a log, this one from a Windows Kodi (same issue no matter the system) , if I don't set "custom dialog" in the settings for the kodi log viewer.

Same error related to "Non-Existent Control 1" in DialogTextViewer.xml 

If this is an issue with the Kodi Log viewer, rather than skin, I understand and can start a bug request for that addon.

Again, there is a workaround, so not a high priority.

Thanks!

[kodi.log](https://github.com/jurialmunkey/skin.arctic.horizon.2/files/9667103/kodi.log)

**Comment by jurialmunkey** [comment]
Thanks. Pretty sure I see what the issue is. Can you try v0.5.7? That should fix it.

The script is expecting a label with id=1 to exist and AH2 doesn't have that control in the textviewer window. So the script is breaking when it tries to write that control because it doesn't have any error handling to deal with that scenario.

id=1 for the heading isn't a [required control for TextViewer](https://kodi.wiki/view/List_of_Built_In_Controls#DialogTextViewer.xml) so I hadn't added it. That script obviously was only tested in Estuary. Anyway, not a big deal for me to add a label with that ID.

**Comment by kcook98765** [comment]
I figured that is what it was (I tried the same change manually to the id and got it to work also). I updated to v0.5.7 and it works now in both windows and osmc..

Thanks!
